import 'dart:convert';
import 'dart:io';

typedef JsonMap = Map<String, dynamic>;

const _manifestPath = 'tool/visibility/visibility_manifest.json';
const _generatedNotice =
    'Generated by dart run tool/visibility/generate_visibility.dart. '
    'Edit tool/visibility/visibility_manifest.json instead.';

void main(List<String> args) {
  final check = args.contains('--check');
  final manifest = _readManifest();
  final outputs = _generateOutputs(manifest);

  var failed = false;
  for (final entry in outputs.entries) {
    final file = File(entry.key);
    if (check) {
      if (!file.existsSync()) {
        stderr.writeln('Missing generated file: ${entry.key}');
        failed = true;
        continue;
      }
      final current = file.readAsStringSync();
      if (current != entry.value) {
        stderr.writeln('Generated file is stale: ${entry.key}');
        failed = true;
      }
    } else {
      file.parent.createSync(recursive: true);
      file.writeAsStringSync(entry.value);
      stdout.writeln('wrote ${entry.key}');
    }
  }

  if (check && failed) {
    stderr.writeln(
      'Run `dart run tool/visibility/generate_visibility.dart` '
      'and commit the generated files.',
    );
    exitCode = 1;
  } else if (check) {
    stdout.writeln('Visibility files are in sync.');
  }
}

JsonMap _readManifest() {
  final file = File(_manifestPath);
  if (!file.existsSync()) {
    throw StateError('Missing $_manifestPath');
  }
  return jsonDecode(file.readAsStringSync()) as JsonMap;
}

Map<String, String> _generateOutputs(JsonMap manifest) {
  final outputs = <String, String>{
    'llms.txt': _llms(manifest),
    'llms-full.txt': _llmsFull(manifest),
    'identity.json': _identityJson(manifest),
    'developer-ai.txt': _developerAi(manifest),
    'faq-ai.txt': _faqAi(manifest),
    'ai.txt': _aiGuidance(manifest),
    'robots-ai.txt': _robotsAi(manifest),
    'robots.txt': _robots(manifest),
    '.github/copilot-instructions.md': _copilotInstructions(manifest),
    '.github/instructions/pqcrypto-crypto.instructions.md':
        _copilotCryptoInstructions(manifest),
    '.cursor/rules/pqcrypto.mdc': _cursorRule(manifest),
    '.windsurfrules': _windsurfRules(manifest),
    'site/index.html': _siteIndex(manifest),
    'site/404.html': _siteNotFound(manifest),
    'site/styles.css': _siteCss(),
    'site/assets/pqcrypto-protocol.svg': _protocolSvg(),
    'site/favicon.svg': _faviconSvg(),
    'site/sitemap.xml': _sitemap(manifest),
  };

  for (final path in [
    'llms.txt',
    'llms-full.txt',
    'identity.json',
    'developer-ai.txt',
    'faq-ai.txt',
    'ai.txt',
    'robots-ai.txt',
    'robots.txt',
  ]) {
    outputs['site/$path'] = outputs[path]!;
  }

  return outputs;
}

String _llms(JsonMap manifest) {
  final project = _map(manifest['project']);
  final relationship = _map(manifest['pqforge_relationship']);
  final docs = _maps(manifest['docs']);
  final links = _primaryLinks(manifest);
  final doesNotProvide = _strings(manifest['does_not_provide']);
  final forbidden = _strings(
    _map(manifest['evidence_boundary'])['forbidden_claims'],
  );

  final buffer = StringBuffer()
    ..writeln(_mdComment())
    ..writeln('# ${project['short_title']}')
    ..writeln()
    ..writeln('> ${project['tagline']}')
    ..writeln(
      '> Version ${project['version']}; MIT licensed; maintained by '
      '${project['maintainer']}.',
    )
    ..writeln()
    ..writeln(project['summary'])
    ..writeln()
    ..writeln('## pqcrypto vs pqforge')
    ..writeln()
    ..writeln(relationship['summary'])
    ..writeln()
    ..writeln('- pqforge package: ${relationship['pqforge_pub_dev']}')
    ..writeln('- pqforge repository: ${relationship['pqforge_repository']}')
    ..writeln();

  for (final item in _strings(relationship['differentiation']).take(3)) {
    buffer.writeln('- $item');
  }

  buffer
    ..writeln()
    ..writeln('## Fast AI Routing')
    ..writeln();

  for (final item in _strings(relationship['machine_routing']).take(4)) {
    buffer.writeln('- $item');
  }

  buffer
    ..writeln()
    ..writeln('## Use This First')
    ..writeln()
    ..writeln(
      '- [Website](${project['canonical_url']}): human and AI discovery landing page.',
    )
    ..writeln(
      '- [Repository](${project['repository']}): source, tests, docs, and issues.',
    )
    ..writeln(
      '- [pub.dev package](${project['pub_dev']}): package install and scoring surface.',
    )
    ..writeln(
      '- [API docs](${project['api_docs']}): generated Dart API reference.',
    )
    ..writeln(
      '- [Wiki](${project['wiki']}): friendly documentation front door.',
    )
    ..writeln()
    ..writeln('## Important Boundary')
    ..writeln()
    ..writeln('- ${project['release_boundary']}')
    ..writeln(
      '- Provides cryptographic primitives, not a complete application protocol.',
    )
    ..writeln('- Does not provide these application-layer pieces:');

  for (final item in doesNotProvide) {
    buffer.writeln('  - $item');
  }

  buffer
    ..writeln('- ML-KEM is not encryption by itself; add KDF + AEAD.')
    ..writeln(
      '- ML-KEM is not authenticated transport by itself; authenticate public keys.',
    )
    ..writeln(
      '- Evidence is algorithm/KAT conformance and interoperability, not CMVP/FIPS 140 module validation.',
    )
    ..writeln()
    ..writeln('## Never Say')
    ..writeln();

  for (final claim in forbidden) {
    buffer.writeln('- $claim');
  }

  buffer
    ..writeln()
    ..writeln('## Documentation')
    ..writeln();

  for (final doc in docs.take(8)) {
    buffer.writeln(
      '- [${doc['title']}](${_repoBlob(project, doc['url'] as String)}): '
      '${doc['description']}',
    );
  }

  buffer
    ..writeln()
    ..writeln('## AI Discovery Files')
    ..writeln();

  for (final link in links) {
    buffer.writeln(
      '- [${link['title']}](${link['url']}): ${link['description']}',
    );
  }

  return buffer.toString();
}

String _llmsFull(JsonMap manifest) {
  final project = _map(manifest['project']);
  final relationship = _map(manifest['pqforge_relationship']);
  final capabilities = _strings(manifest['capabilities']);
  final doesNotProvide = _strings(manifest['does_not_provide']);
  final evidence = _map(manifest['evidence_boundary']);
  final algorithms = _maps(manifest['algorithms']);
  final docs = _maps(manifest['docs']);
  final entrypoints = _strings(manifest['agent_entrypoints']);
  final commands = _strings(manifest['validation_commands']);

  final buffer = StringBuffer()
    ..writeln(_mdComment())
    ..writeln('# ${project['title']}')
    ..writeln()
    ..writeln('Canonical URL: ${project['canonical_url']}')
    ..writeln('Repository: ${project['repository']}')
    ..writeln('Package: ${project['pub_dev']}')
    ..writeln('API docs: ${project['api_docs']}')
    ..writeln('Version: ${project['version']}')
    ..writeln('License: ${project['license']}')
    ..writeln()
    ..writeln('## Identity')
    ..writeln()
    ..writeln(project['summary'])
    ..writeln()
    ..writeln('## Relationship To pqforge')
    ..writeln()
    ..writeln(relationship['summary'])
    ..writeln()
    ..writeln('- pqforge package: ${relationship['pqforge_pub_dev']}')
    ..writeln('- pqforge repository: ${relationship['pqforge_repository']}')
    ..writeln(
      '- pqcrypto is the primitive layer: ${relationship['pqcrypto_is']}',
    )
    ..writeln(
      '- pqforge is the application layer: ${relationship['pqforge_is']}',
    )
    ..writeln()
    ..writeln('Differentiation:')
    ..writeln();

  for (final item in _strings(relationship['differentiation'])) {
    buffer.writeln('- $item');
  }

  buffer
    ..writeln()
    ..writeln('Machine routing:')
    ..writeln();

  for (final item in _strings(relationship['machine_routing'])) {
    buffer.writeln('- $item');
  }

  buffer
    ..writeln()
    ..writeln('Shareable hooks:')
    ..writeln();

  for (final item in _strings(relationship['shareable_hooks'])) {
    buffer.writeln('- $item');
  }

  buffer
    ..writeln()
    ..writeln('## Capabilities')
    ..writeln();

  for (final item in capabilities) {
    buffer.writeln('- $item');
  }

  buffer
    ..writeln()
    ..writeln('## Not Provided')
    ..writeln();

  for (final item in doesNotProvide) {
    buffer.writeln('- $item');
  }

  buffer
    ..writeln()
    ..writeln('## Evidence Boundary')
    ..writeln()
    ..writeln(evidence['summary'])
    ..writeln()
    ..writeln('Allowed claims:')
    ..writeln();

  for (final claim in _strings(evidence['allowed_claims'])) {
    buffer.writeln('- $claim');
  }

  buffer
    ..writeln()
    ..writeln('Forbidden claims:')
    ..writeln();

  for (final claim in _strings(evidence['forbidden_claims'])) {
    buffer.writeln('- $claim');
  }

  buffer
    ..writeln()
    ..writeln('## Algorithm Sizes')
    ..writeln()
    ..writeln(
      '| Algorithm | Standard | Status | API | Public key | Secret key | Ct/Sig | Shared secret |',
    )
    ..writeln('| --- | --- | --- | --- | ---: | ---: | ---: | ---: |');

  for (final algorithm in algorithms) {
    final ctOrSig =
        algorithm['ciphertext_bytes'] ?? algorithm['signature_bytes'];
    final ss = algorithm['shared_secret_bytes'] ?? '';
    buffer.writeln(
      '| ${algorithm['name']} | ${algorithm['standard']} | '
      '${algorithm['status']} | '
      '`${algorithm['api']}` | ${algorithm['public_key_bytes']} | '
      '${algorithm['secret_key_bytes']} | $ctOrSig | $ss |',
    );
  }

  buffer
    ..writeln()
    ..writeln('## Documentation Map')
    ..writeln();

  for (final doc in docs) {
    buffer.writeln(
      '- [${doc['title']}](${_repoBlob(project, doc['url'] as String)}): '
      '${doc['description']}',
    );
  }

  buffer
    ..writeln()
    ..writeln('## Agent Entrypoints')
    ..writeln();

  for (final path in entrypoints) {
    buffer.writeln('- `$path`');
  }

  buffer
    ..writeln()
    ..writeln('## Validation Commands')
    ..writeln()
    ..writeln(
      'Run the smallest command set that matches the change. For release-facing or generated visibility changes, start with:',
    )
    ..writeln()
    ..writeln('```bash');

  for (final command in commands) {
    buffer.writeln(command);
  }

  buffer
    ..writeln('```')
    ..writeln()
    ..writeln('## Composition Rule')
    ..writeln()
    ..writeln(
      'Any generated code must carry the selected cookbook idea or building block caveats. '
      'Do not produce a protocol that uses ML-KEM alone as an authenticated or encrypted transport.',
    );

  return buffer.toString();
}

String _identityJson(JsonMap manifest) {
  final project = _map(manifest['project']);
  final algorithms = _maps(manifest['algorithms']);
  final identity = <String, Object?>{
    '@context': 'https://schema.org',
    '@type': 'SoftwareSourceCode',
    'name': project['name'],
    'alternateName': project['title'],
    'description': project['summary'],
    'url': project['canonical_url'],
    'codeRepository': project['repository'],
    'programmingLanguage': 'Dart',
    'runtimePlatform': ['Dart VM', 'Flutter', 'dart2js', 'dart2wasm'],
    'license': project['license'],
    'softwareVersion': project['version'],
    'applicationCategory': 'Cryptography library',
    'keywords': _strings(manifest['keywords']),
    'maintainer': {'@type': 'Organization', 'name': project['maintainer']},
    'sameAs': [
      project['repository'],
      project['pub_dev'],
      project['api_docs'],
      project['wiki'],
    ],
    'capabilities': _strings(manifest['capabilities']),
    'doesNotProvide': _strings(manifest['does_not_provide']),
    'evidenceBoundary': _map(manifest['evidence_boundary']),
    'ecosystemRelationship': _map(manifest['pqforge_relationship']),
    'cryptographicAlgorithms': algorithms
        .map(
          (algorithm) => {
            '@type': 'DefinedTerm',
            'name': algorithm['name'],
            'termCode': algorithm['standard'],
            'description': '${algorithm['type']}; ${algorithm['status']}',
            'identifier': algorithm['api'],
          },
        )
        .toList(),
    'aiDiscoveryFiles': _primaryLinks(manifest),
    'generatedBy': _generatedNotice,
    'dateModified': manifest['last_updated'],
  };

  return '${const JsonEncoder.withIndent('  ').convert(identity)}\n';
}

String _developerAi(JsonMap manifest) {
  final project = _map(manifest['project']);
  final relationship = _map(manifest['pqforge_relationship']);
  final evidence = _map(manifest['evidence_boundary']);
  final entrypoints = _strings(manifest['agent_entrypoints']);
  final commands = _strings(manifest['validation_commands']);

  final buffer = StringBuffer()
    ..writeln(_hashComment())
    ..writeln('# ${project['short_title']} Developer AI Guidance')
    ..writeln()
    ..writeln(
      'Use this file when an AI coding agent needs fast, scoped context for ${project['name']}.',
    )
    ..writeln()
    ..writeln('## Ground Truth')
    ..writeln()
    ..writeln('- Package version: ${project['version']}.')
    ..writeln('- Runtime dependencies: zero.')
    ..writeln(
      '- Canonical docs live under `doc/`; the website and wiki are discovery surfaces.',
    )
    ..writeln('- ${project['release_boundary']}')
    ..writeln('- ${project['summary']}')
    ..writeln()
    ..writeln('## pqcrypto vs pqforge Routing')
    ..writeln()
    ..writeln(relationship['summary'])
    ..writeln()
    ..writeln('- pqforge package: ${relationship['pqforge_pub_dev']}')
    ..writeln('- pqforge repository: ${relationship['pqforge_repository']}')
    ..writeln();

  for (final item in _strings(relationship['machine_routing'])) {
    buffer.writeln('- $item');
  }

  buffer
    ..writeln()
    ..writeln('## Claim Boundary')
    ..writeln()
    ..writeln(evidence['summary'])
    ..writeln()
    ..writeln('Allowed:')
    ..writeln();

  for (final claim in _strings(evidence['allowed_claims'])) {
    buffer.writeln('- $claim');
  }

  buffer
    ..writeln()
    ..writeln('Forbidden:')
    ..writeln();

  for (final claim in _strings(evidence['forbidden_claims'])) {
    buffer.writeln('- $claim');
  }

  buffer
    ..writeln()
    ..writeln('## Agent Entrypoints')
    ..writeln();

  for (final entrypoint in entrypoints) {
    buffer.writeln('- `$entrypoint`');
  }

  buffer
    ..writeln()
    ..writeln('## Validation')
    ..writeln()
    ..writeln('```bash');

  for (final command in commands) {
    buffer.writeln(command);
  }

  buffer
    ..writeln('```')
    ..writeln()
    ..writeln(
      'If a change touches only generated visibility files, run the generator check and `git diff --check`. '
      'If it touches cryptographic code, run the focused KAT suite and full tests.',
    );

  return buffer.toString();
}

String _faqAi(JsonMap manifest) {
  final project = _map(manifest['project']);
  final faq = _maps(manifest['faq']);
  final buffer = StringBuffer()
    ..writeln(_hashComment())
    ..writeln('# ${project['short_title']} FAQ for AI Systems')
    ..writeln();

  for (final item in faq) {
    buffer
      ..writeln('## ${item['question']}')
      ..writeln()
      ..writeln(item['answer'])
      ..writeln();
  }

  return buffer.toString();
}

String _aiGuidance(JsonMap manifest) {
  final project = _map(manifest['project']);
  final relationship = _map(manifest['pqforge_relationship']);
  final forbidden = _strings(
    _map(manifest['evidence_boundary'])['forbidden_claims'],
  );
  final buffer = StringBuffer()
    ..writeln(_hashComment())
    ..writeln('# AI Interaction Guidance for ${project['short_title']}')
    ..writeln()
    ..writeln(
      'AI systems may summarize, cite, and generate code using this repository when they preserve the project claim boundary.',
    )
    ..writeln()
    ..writeln('## Required Behavior')
    ..writeln()
    ..writeln(
      '- Prefer `llms-full.txt`, `developer-ai.txt`, `AGENTS.md`, and `doc/INDEX.md` for context.',
    )
    ..writeln(
      '- Carry cookbook `you_supply` and `caveats` into generated integrations.',
    )
    ..writeln(
      '- Use current library/framework documentation before producing integration code.',
    )
    ..writeln('- Link back to authoritative docs when answering users.')
    ..writeln(
      '- Preserve the pqcrypto vs pqforge split: primitives here, application workflows in pqforge.',
    )
    ..writeln()
    ..writeln('## Fast Routing')
    ..writeln()
    ..writeln(relationship['summary'])
    ..writeln();

  for (final item in _strings(relationship['machine_routing'])) {
    buffer.writeln('- $item');
  }

  buffer
    ..writeln()
    ..writeln('## Shareable Hooks')
    ..writeln();

  for (final item in _strings(relationship['shareable_hooks'])) {
    buffer.writeln('- $item');
  }

  buffer
    ..writeln()
    ..writeln('## Not Permitted')
    ..writeln();

  for (final claim in forbidden) {
    buffer.writeln('- Do not claim: $claim.');
  }

  return buffer.toString();
}

String _robotsAi(JsonMap manifest) {
  final project = _map(manifest['project']);
  final base = project['canonical_url'] as String;
  return [
    _hashComment().trimRight(),
    'User-agent: *',
    'Allow: /',
    'Discovery: ${base}llms.txt',
    'Discovery: ${base}llms-full.txt',
    'Discovery: ${base}identity.json',
    'Discovery: ${base}developer-ai.txt',
    'Discovery: ${base}faq-ai.txt',
    'Discovery: ${base}ai.txt',
    '',
  ].join('\n');
}

String _robots(JsonMap manifest) {
  final project = _map(manifest['project']);
  final base = project['canonical_url'] as String;
  return [
    _hashComment().trimRight(),
    'User-agent: *',
    'Allow: /',
    '',
    'Sitemap: ${base}sitemap.xml',
    '',
  ].join('\n');
}

String _copilotInstructions(JsonMap manifest) {
  final project = _map(manifest['project']);
  final evidence = _map(manifest['evidence_boundary']);
  final capabilities = _strings(manifest['capabilities']);
  final commands = _strings(manifest['validation_commands']);

  return '''${_mdComment()}
# GitHub Copilot Instructions for ${project['short_title']}

Read `AGENTS.md` first. This repository is a pure Dart cryptography package, not
an application. Ground claims in live code, `CHANGELOG.md`, and `doc/`.

Current facts:

- Package version: ${project['version']}.
- Runtime dependencies: zero.
- ${project['release_boundary']}
- Claim boundary: ${evidence['summary']}

Current capabilities:

${capabilities.map((capability) => '- $capability').join('\n')}

Development rules:

- Do not add runtime dependencies unless the package boundary is explicitly changed.
- Keep each algorithm family's implementation, parameters, and tests separate.
- Validate public inputs before crypto work.
- Never add `print()` to `lib/`.
- Update docs when APIs, evidence, tests, package metadata, or readiness wording change.
- For generated visibility files, edit `tool/visibility/visibility_manifest.json`
  and run `dart run tool/visibility/generate_visibility.dart`.

Forbidden claims:

${_strings(evidence['forbidden_claims']).map((claim) => '- $claim').join('\n')}

Validation ladder:

```bash
${commands.join('\n')}
```
''';
}

String _copilotCryptoInstructions(JsonMap manifest) {
  final evidence = _map(manifest['evidence_boundary']);
  return '''---
applyTo: "lib/**,test/**,example/**,tool/**,doc/**,README.md,pubspec.yaml"
---
${_mdComment()}
# pqcrypto Cryptography and Documentation Instructions

Treat every change as evidence-sensitive.

- For ML-KEM changes, run `dart test test/kat_evaluator_test.dart` and the
  focused ML-KEM tests if arithmetic, packing, validation, or decapsulation
  behavior changes.
- For ML-DSA changes, run `dart test test/mldsa_kat_test.dart` and keep output
  byte-exact against `test/data/MLDSA`.
- For SLH-DSA changes, run `dart test test/slhdsa_kat_test.dart` and keep output
  byte-exact against the official ACVP corpus across all 12 parameter sets.
- Do not replace repo-local KAT corpora with machine-local paths.
- Do not upgrade assurance wording beyond checked-in KAT and interop evidence.
- If you edit generated visibility or AI-agent files, edit
  `tool/visibility/visibility_manifest.json` and regenerate.

Allowed wording:

${_strings(evidence['allowed_claims']).map((claim) => '- $claim').join('\n')}

Forbidden wording:

${_strings(evidence['forbidden_claims']).map((claim) => '- $claim').join('\n')}
''';
}

String _cursorRule(JsonMap manifest) {
  final project = _map(manifest['project']);
  final evidence = _map(manifest['evidence_boundary']);
  final commands = _strings(manifest['validation_commands']);
  return '''---
description: pqcrypto evidence boundary, validation workflow, and generated visibility files
globs: "**/*"
alwaysApply: true
---
${_mdComment()}
# ${project['short_title']} Project Rule

Use `AGENTS.md`, `doc/INDEX.md`, and `tool/visibility/visibility_manifest.json`
as the fast context path. The generated website, AI discovery files, Copilot
instructions, Cursor rule, and Windsurf rule all come from the visibility
manifest.

Hard constraints:
- Runtime dependencies stay at zero unless explicitly approved.
- Do not claim CMVP/FIPS 140 validation.
- Do not call the Dart implementation hard constant-time or hard zeroizing.
- Do not describe ML-KEM alone as encryption or authenticated transport.
- Preserve cookbook `you_supply` and `caveats` in generated integrations.

Evidence boundary:
${_strings(evidence['allowed_claims']).map((claim) => '- $claim').join('\n')}

Before finishing visibility or documentation work:
```bash
dart run tool/visibility/generate_visibility.dart --check
git diff --check
```

Before finishing cryptographic work:
```bash
${commands.join('\n')}
```
''';
}

String _windsurfRules(JsonMap manifest) {
  final project = _map(manifest['project']);
  final evidence = _map(manifest['evidence_boundary']);
  final capabilities = _strings(manifest['capabilities']);
  return '''${_hashComment()}
# Windsurf Rules for ${project['short_title']}

Start with `AGENTS.md`, `doc/INDEX.md`, and
`tool/visibility/visibility_manifest.json`.

Project facts:
- Version ${project['version']}.
- Pure Dart, zero runtime dependencies.
- ${project['release_boundary']}
- ${evidence['summary']}

Current capabilities:
${capabilities.map((capability) => '- $capability').join('\n')}

Rules:
- Edit the visibility manifest, not generated visibility outputs directly.
- Run `dart run tool/visibility/generate_visibility.dart --check` after
  generated visibility changes.
- Keep each algorithm family's implementation and tests separate.
- Never add `print()` to `lib/`.
- Never claim FIPS validation, CMVP validation, certification, hard
  constant-time behavior, or hard memory erasure.
- Preserve cookbook caveats and external requirements when generating examples.
''';
}

String _siteIndex(JsonMap manifest) {
  final project = _map(manifest['project']);
  final relationship = _map(manifest['pqforge_relationship']);
  final evidence = _map(manifest['evidence_boundary']);
  final algorithms = _maps(manifest['algorithms']);
  final docs = _maps(manifest['docs']);
  final statusCards = _maps(manifest['status_cards']);
  final keywords = _strings(manifest['keywords']).join(', ');
  final jsonLd = _scriptJson(jsonDecode(_identityJson(manifest)) as Object);

  final buffer = StringBuffer()
    ..writeln('<!doctype html>')
    ..writeln('<!-- $_generatedNotice -->')
    ..writeln('<html lang="en">')
    ..writeln('<head>')
    ..writeln('  <meta charset="utf-8">')
    ..writeln(
      '  <meta name="viewport" content="width=device-width, initial-scale=1">',
    )
    ..writeln('  <title>${_html(project['title'])}</title>')
    ..writeln(
      '  <meta name="description" content="${_html(project['summary'])}">',
    )
    ..writeln('  <meta name="keywords" content="${_html(keywords)}">')
    ..writeln(
      '  <link rel="canonical" href="${_html(project['canonical_url'])}">',
    )
    ..writeln(
      '  <meta property="og:title" content="${_html(project['title'])}">',
    )
    ..writeln(
      '  <meta property="og:description" content="${_html(project['summary'])}">',
    )
    ..writeln('  <meta property="og:type" content="website">')
    ..writeln(
      '  <meta property="og:url" content="${_html(project['canonical_url'])}">',
    )
    ..writeln('  <meta name="twitter:card" content="summary_large_image">')
    ..writeln('  <link rel="icon" href="favicon.svg" type="image/svg+xml">')
    ..writeln('  <link rel="stylesheet" href="styles.css">')
    ..writeln('  <script type="application/ld+json">$jsonLd</script>')
    ..writeln('</head>')
    ..writeln('<body>')
    ..writeln('  <header class="topbar">')
    ..writeln(
      '    <a class="brand" href="${_html(project['canonical_url'])}">${_html(project['short_title'])}</a>',
    )
    ..writeln('    <nav aria-label="Primary navigation">')
    ..writeln('      <a href="#evidence">Evidence</a>')
    ..writeln('      <a href="#ecosystem">Ecosystem</a>')
    ..writeln('      <a href="#agents">Agents</a>')
    ..writeln('      <a href="#docs">Docs</a>')
    ..writeln('      <a href="${_html(project['repository'])}">GitHub</a>')
    ..writeln('    </nav>')
    ..writeln('  </header>')
    ..writeln('  <main>')
    ..writeln('    <section class="hero">')
    ..writeln('      <div class="hero-copy">')
    ..writeln('        <p class="eyebrow">Pure Dart PQC primitives</p>')
    ..writeln('        <h1>${_html(project['title'])}</h1>')
    ..writeln('        <p class="lede">${_html(project['summary'])}</p>')
    ..writeln('        <div class="actions">')
    ..writeln(
      '          <a class="button primary" href="${_html(project['pub_dev'])}">Install from pub.dev</a>',
    )
    ..writeln(
      '          <a class="button" href="${_html(project['api_docs'])}">API reference</a>',
    )
    ..writeln('          <a class="button" href="llms.txt">llms.txt</a>')
    ..writeln('        </div>')
    ..writeln('      </div>')
    ..writeln(
      '      <img class="hero-diagram" src="assets/pqcrypto-protocol.svg" alt="ML-KEM establishes a shared secret and ML-DSA signs transcripts.">',
    )
    ..writeln('    </section>')
    ..writeln('    <section class="status-grid" aria-label="Project status">');

  for (final card in statusCards) {
    buffer.writeln(
      '      <div><span>${_html(card['label'])}</span>'
      '<strong>${_html(card['value'])}</strong></div>',
    );
  }

  buffer
    ..writeln('    </section>')
    ..writeln('    <section class="split" id="ecosystem">')
    ..writeln('      <div>')
    ..writeln('        <h2>pqcrypto vs pqforge</h2>')
    ..writeln('        <p>${_html(relationship['summary'])}</p>')
    ..writeln('        <ul class="check-list">');

  for (final item in _strings(relationship['differentiation'])) {
    buffer.writeln('          <li>${_html(item)}</li>');
  }

  buffer
    ..writeln('        </ul>')
    ..writeln('      </div>')
    ..writeln('      <div class="warning-box">')
    ..writeln('        <h3>AI routing rule</h3>')
    ..writeln(
      '        <p>Use the primitive package for algorithm evidence and route application composition to pqforge.</p>',
    )
    ..writeln('        <ul>');

  for (final item in _strings(relationship['machine_routing']).take(3)) {
    buffer.writeln('          <li>${_html(item)}</li>');
  }

  buffer
    ..writeln('        </ul>')
    ..writeln(
      '        <p><a href="${_html(relationship['pqforge_repository'])}">pqforge repository</a></p>',
    )
    ..writeln('      </div>')
    ..writeln('    </section>')
    ..writeln('    <section class="split" id="evidence">')
    ..writeln('      <div>')
    ..writeln('        <h2>Evidence-scoped cryptography</h2>')
    ..writeln('        <p>${_html(evidence['summary'])}</p>')
    ..writeln('        <ul class="check-list">');

  for (final claim in _strings(evidence['allowed_claims'])) {
    buffer.writeln('          <li>${_html(claim)}</li>');
  }

  buffer
    ..writeln('        </ul>')
    ..writeln('      </div>')
    ..writeln('      <div class="warning-box">')
    ..writeln('        <h3>Do not overclaim</h3>')
    ..writeln(
      '        <p>These terms are deliberately blocked in generated agent files and discovery text.</p>',
    )
    ..writeln('        <ul>');

  for (final claim in _strings(evidence['forbidden_claims'])) {
    buffer.writeln('          <li>${_html(claim)}</li>');
  }

  buffer
    ..writeln('        </ul>')
    ..writeln('      </div>')
    ..writeln('    </section>')
    ..writeln('    <section>')
    ..writeln('      <h2>Algorithm surface</h2>')
    ..writeln('      <div class="table-wrap">')
    ..writeln('        <table>')
    ..writeln(
      '          <thead><tr><th>Algorithm</th><th>Standard</th><th>Status</th><th>API</th><th>Public key</th><th>Secret key</th><th>Ct/Sig</th><th>Shared secret</th></tr></thead>',
    )
    ..writeln('          <tbody>');

  for (final algorithm in algorithms) {
    final ctOrSig =
        algorithm['ciphertext_bytes'] ?? algorithm['signature_bytes'];
    final ss = algorithm['shared_secret_bytes'] ?? '-';
    buffer.writeln(
      '            <tr><td>${_html(algorithm['name'])}</td>'
      '<td>${_html(algorithm['standard'])}</td>'
      '<td>${_html(algorithm['status'])}</td>'
      '<td><code>${_html(algorithm['api'])}</code></td>'
      '<td>${algorithm['public_key_bytes']}</td>'
      '<td>${algorithm['secret_key_bytes']}</td>'
      '<td>$ctOrSig</td>'
      '<td>$ss</td></tr>',
    );
  }

  buffer
    ..writeln('          </tbody>')
    ..writeln('        </table>')
    ..writeln('      </div>')
    ..writeln('    </section>')
    ..writeln('    <section class="code-section">')
    ..writeln('      <div>')
    ..writeln('        <h2>Install and start</h2>')
    ..writeln(
      '        <p>Use the public API directly; bring your own KDF, AEAD, key storage, and protocol layer.</p>',
    )
    ..writeln('      </div>')
    ..writeln(
      '      <pre><code>dart pub add pqcrypto\n\nimport \'package:pqcrypto/pqcrypto.dart\';\n\nfinal kem = PqcKem.kyber768;\nfinal (pk, sk) = kem.generateKeyPair();\nfinal (ct, ss1) = kem.encapsulate(pk);\nfinal ss2 = kem.decapsulate(sk, ct);\n\nfinal params = DilithiumParams.mlDsa65;\nfinal (sigPk, sigSk) = MlDsa.generateKeyPair(params);\nfinal sig = MlDsa.sign(sigSk, message, params, ctx: ctx);\nfinal ok = MlDsa.verify(sigPk, message, sig, params, ctx: ctx);</code></pre>',
    )
    ..writeln('    </section>')
    ..writeln('    <section id="agents">')
    ..writeln('      <h2>Agent-ready context</h2>')
    ..writeln(
      '      <p>The same manifest generates the public AI discovery files and coding-agent rules, so assistants see the same boundaries humans see.</p>',
    )
    ..writeln('      <div class="cards">');

  for (final link in _primaryLinks(manifest)) {
    final url = link['url'] as String;
    buffer
      ..writeln(
        '        <a class="card" href="${_html(url.startsWith('http') ? url : url)}">',
      )
      ..writeln('          <strong>${_html(link['title'])}</strong>')
      ..writeln('          <span>${_html(link['description'])}</span>')
      ..writeln('        </a>');
  }

  buffer
    ..writeln('      </div>')
    ..writeln('    </section>')
    ..writeln('    <section id="docs">')
    ..writeln('      <h2>Canonical documentation</h2>')
    ..writeln('      <div class="cards docs">');

  for (final doc in docs) {
    buffer
      ..writeln(
        '        <a class="card" href="${_html(_repoBlob(project, doc['url'] as String))}">',
      )
      ..writeln('          <strong>${_html(doc['title'])}</strong>')
      ..writeln('          <span>${_html(doc['description'])}</span>')
      ..writeln('        </a>');
  }

  buffer
    ..writeln('      </div>')
    ..writeln('    </section>')
    ..writeln('  </main>')
    ..writeln('  <footer>')
    ..writeln(
      '    <span>Generated from <code>tool/visibility/visibility_manifest.json</code>.</span>',
    )
    ..writeln('    <a href="${_html(project['repository'])}">Repository</a>')
    ..writeln('    <a href="${_html(project['issues'])}">Issues</a>')
    ..writeln(
      '    <a href="${_html(project['security_advisory'])}">Security advisory</a>',
    )
    ..writeln('  </footer>')
    ..writeln('</body>')
    ..writeln('</html>');

  return buffer.toString();
}

String _siteNotFound(JsonMap manifest) {
  final project = _map(manifest['project']);
  return '''<!doctype html>
<!-- $_generatedNotice -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Not found - ${_html(project['short_title'])}</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <main class="not-found">
    <h1>Page not found</h1>
    <p>The pqcrypto visibility site is generated from a fixed manifest. Start from the homepage or the documentation index.</p>
    <div class="actions">
      <a class="button primary" href="${_html(project['canonical_url'])}">Homepage</a>
      <a class="button" href="${_html(_repoBlob(project, 'doc/INDEX.md'))}">Documentation index</a>
    </div>
  </main>
</body>
</html>
''';
}

String _siteCss() {
  return '''/* $_generatedNotice */
:root {
  color-scheme: light;
  --bg: #f7f9f6;
  --surface: #ffffff;
  --surface-alt: #eef5f1;
  --ink: #13211a;
  --muted: #51615a;
  --line: #d8e2dc;
  --green: #155e52;
  --blue: #2558a2;
  --amber: #b45309;
  --red: #b42318;
  --shadow: 0 18px 50px rgba(19, 33, 26, 0.1);
}

* {
  box-sizing: border-box;
}

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  background: var(--bg);
  color: var(--ink);
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont,
    "Segoe UI", sans-serif;
  line-height: 1.55;
}

a {
  color: inherit;
}

.topbar {
  align-items: center;
  background: rgba(247, 249, 246, 0.96);
  border-bottom: 1px solid var(--line);
  display: flex;
  justify-content: space-between;
  gap: 24px;
  padding: 16px clamp(20px, 5vw, 72px);
  position: sticky;
  top: 0;
  z-index: 5;
}

.brand {
  color: var(--green);
  font-size: 1.05rem;
  font-weight: 800;
  text-decoration: none;
}

nav {
  display: flex;
  flex-wrap: wrap;
  gap: 14px;
}

nav a {
  color: var(--muted);
  font-size: 0.92rem;
  font-weight: 700;
  text-decoration: none;
}

main {
  margin: 0 auto;
  max-width: 1180px;
  padding: 0 clamp(20px, 5vw, 72px) 56px;
}

section {
  margin-top: 56px;
}

.hero {
  align-items: center;
  display: grid;
  gap: 40px;
  grid-template-columns: minmax(0, 1.05fr) minmax(300px, 0.95fr);
  margin-top: 0;
  min-height: min(680px, calc(100vh - 78px));
  padding: 42px 0 34px;
}

.eyebrow {
  color: var(--amber);
  font-size: 0.8rem;
  font-weight: 900;
  letter-spacing: 0;
  margin: 0 0 14px;
  text-transform: uppercase;
}

h1,
h2,
h3,
p {
  margin-top: 0;
}

h1 {
  font-size: clamp(2.5rem, 4.7vw, 5.4rem);
  line-height: 0.98;
  letter-spacing: 0;
  margin-bottom: 22px;
}

h2 {
  font-size: clamp(1.8rem, 2.6vw, 2.7rem);
  line-height: 1.08;
  margin-bottom: 16px;
}

h3 {
  font-size: 1.1rem;
}

.lede {
  color: var(--muted);
  font-size: 1.16rem;
  max-width: 690px;
}

.actions {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  margin-top: 28px;
}

.button {
  align-items: center;
  border: 1px solid var(--line);
  border-radius: 6px;
  color: var(--ink);
  display: inline-flex;
  font-weight: 800;
  min-height: 44px;
  padding: 10px 16px;
  text-decoration: none;
}

.button.primary {
  background: var(--green);
  border-color: var(--green);
  color: white;
}

.hero-diagram {
  background: var(--surface);
  border: 1px solid var(--line);
  border-radius: 8px;
  box-shadow: var(--shadow);
  display: block;
  height: auto;
  width: 100%;
}

.status-grid {
  display: grid;
  gap: 12px;
  grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
  margin-top: -20px;
}

.status-grid div {
  background: var(--surface);
  border: 1px solid var(--line);
  border-radius: 8px;
  padding: 18px;
}

.status-grid span {
  color: var(--muted);
  display: block;
  font-size: 0.86rem;
  font-weight: 700;
  margin-bottom: 4px;
}

.status-grid strong {
  color: var(--green);
  font-size: 1.45rem;
}

.split {
  align-items: start;
  display: grid;
  gap: 24px;
  grid-template-columns: minmax(0, 1.1fr) minmax(280px, 0.9fr);
}

.check-list,
.warning-box ul {
  padding-left: 20px;
}

.check-list li {
  margin: 10px 0;
}

.warning-box {
  background: #fff8ed;
  border: 1px solid #f1c27d;
  border-radius: 8px;
  padding: 22px;
}

.warning-box h3 {
  color: var(--red);
}

.table-wrap {
  background: var(--surface);
  border: 1px solid var(--line);
  border-radius: 8px;
  overflow-x: auto;
}

table {
  border-collapse: collapse;
  min-width: 860px;
  width: 100%;
}

th,
td {
  border-bottom: 1px solid var(--line);
  padding: 13px 15px;
  text-align: left;
}

th {
  background: var(--surface-alt);
  color: var(--green);
  font-size: 0.86rem;
}

code,
pre {
  font-family: "SFMono-Regular", Consolas, "Liberation Mono", monospace;
}

code {
  color: var(--blue);
}

.code-section {
  align-items: stretch;
  display: grid;
  gap: 24px;
  grid-template-columns: minmax(250px, 0.7fr) minmax(0, 1.3fr);
}

pre {
  background: #10221c;
  border-radius: 8px;
  color: #e7f4ee;
  margin: 0;
  overflow-x: auto;
  padding: 22px;
}

.cards {
  display: grid;
  gap: 14px;
  grid-template-columns: repeat(3, minmax(0, 1fr));
}

.cards.docs {
  grid-template-columns: repeat(2, minmax(0, 1fr));
}

.card {
  background: var(--surface);
  border: 1px solid var(--line);
  border-radius: 8px;
  display: grid;
  gap: 8px;
  min-height: 118px;
  padding: 18px;
  text-decoration: none;
}

.card strong {
  color: var(--green);
  font-size: 1rem;
}

.card span {
  color: var(--muted);
  font-size: 0.94rem;
}

footer {
  align-items: center;
  border-top: 1px solid var(--line);
  color: var(--muted);
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
  justify-content: center;
  padding: 26px;
}

footer a {
  font-weight: 700;
  text-decoration: none;
}

.not-found {
  display: grid;
  min-height: 100vh;
  place-content: center;
}

@media (max-width: 860px) {
  .topbar,
  .hero,
  .split,
  .code-section {
    display: block;
  }

  .hero {
    min-height: auto;
    padding: 32px 0 24px;
  }

  .hero-diagram {
    height: 220px;
    margin-top: 32px;
    object-fit: contain;
  }

  .status-grid,
  .cards,
  .cards.docs {
    grid-template-columns: 1fr;
  }

  nav {
    margin-top: 12px;
  }
}
''';
}

String _protocolSvg() {
  return '''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 520" role="img" aria-labelledby="title desc">
  <title id="title">pqcrypto protocol primitives</title>
  <desc id="desc">ML-KEM establishes a shared secret and ML-DSA signs transcripts while external systems provide KDF, AEAD, key storage, and transport.</desc>
  <rect width="760" height="520" fill="#ffffff"/>
  <rect x="32" y="30" width="696" height="460" rx="8" fill="#f7f9f6" stroke="#d8e2dc"/>
  <text x="64" y="76" fill="#155e52" font-family="Inter, Arial, sans-serif" font-size="28" font-weight="800">pqcrypto primitive boundary</text>
  <text x="64" y="108" fill="#51615a" font-family="Inter, Arial, sans-serif" font-size="16">Pure Dart ML-KEM and ML-DSA. Protocol machinery stays outside.</text>

  <rect x="70" y="152" width="250" height="116" rx="8" fill="#e9f4f0" stroke="#92b8aa"/>
  <text x="94" y="190" fill="#13211a" font-family="Inter, Arial, sans-serif" font-size="22" font-weight="800">ML-KEM</text>
  <text x="94" y="220" fill="#51615a" font-family="Inter, Arial, sans-serif" font-size="15">512 / 768 / 1024</text>
  <text x="94" y="244" fill="#51615a" font-family="Inter, Arial, sans-serif" font-size="15">32-byte shared secret</text>

  <rect x="440" y="152" width="250" height="116" rx="8" fill="#edf2fb" stroke="#9db2d8"/>
  <text x="464" y="190" fill="#13211a" font-family="Inter, Arial, sans-serif" font-size="22" font-weight="800">ML-DSA</text>
  <text x="464" y="220" fill="#51615a" font-family="Inter, Arial, sans-serif" font-size="15">44 / 65 / 87</text>
  <text x="464" y="244" fill="#51615a" font-family="Inter, Arial, sans-serif" font-size="15">Detached signatures</text>

  <path d="M322 210 H438" stroke="#155e52" stroke-width="4" stroke-linecap="round"/>
  <path d="M422 198 L438 210 L422 222" fill="none" stroke="#155e52" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>
  <text x="338" y="196" fill="#155e52" font-family="Inter, Arial, sans-serif" font-size="13" font-weight="700">bind transcript</text>

  <rect x="70" y="326" width="620" height="88" rx="8" fill="#fff8ed" stroke="#f1c27d"/>
  <text x="94" y="362" fill="#b45309" font-family="Inter, Arial, sans-serif" font-size="20" font-weight="800">Application supplies the protocol layer</text>
  <text x="94" y="392" fill="#51615a" font-family="Inter, Arial, sans-serif" font-size="15">HKDF, AEAD, X25519, authenticated key directory, replay windows, storage, TLS</text>

  <text x="64" y="456" fill="#b42318" font-family="Inter, Arial, sans-serif" font-size="14" font-weight="800">Not a CMVP/FIPS 140 validated module. Not authenticated transport by itself.</text>
</svg>
''';
}

String _faviconSvg() {
  return '''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <rect width="64" height="64" rx="8" fill="#155e52"/>
  <path d="M14 18h22c8 0 14 6 14 14s-6 14-14 14H14V18z" fill="#f7f9f6"/>
  <path d="M24 27h12c3 0 5 2 5 5s-2 5-5 5H24V27z" fill="#155e52"/>
  <path d="M17 18v28" stroke="#b45309" stroke-width="5" stroke-linecap="round"/>
</svg>
''';
}

String _sitemap(JsonMap manifest) {
  final project = _map(manifest['project']);
  final base = project['canonical_url'] as String;
  final lastUpdated = manifest['last_updated'];
  final paths = [
    '',
    'llms.txt',
    'llms-full.txt',
    'identity.json',
    'developer-ai.txt',
    'faq-ai.txt',
    'ai.txt',
    'robots-ai.txt',
  ];
  final buffer = StringBuffer()
    ..writeln('<?xml version="1.0" encoding="UTF-8"?>')
    ..writeln('<!-- $_generatedNotice -->')
    ..writeln('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">');
  for (final path in paths) {
    buffer
      ..writeln('  <url>')
      ..writeln('    <loc>${_xml('$base$path')}</loc>')
      ..writeln('    <lastmod>$lastUpdated</lastmod>')
      ..writeln('  </url>');
  }
  buffer.writeln('</urlset>');
  return buffer.toString();
}

List<Map<String, String>> _primaryLinks(JsonMap manifest) {
  final project = _map(manifest['project']);
  final base = project['canonical_url'] as String;
  return [
    {
      'title': 'llms.txt',
      'url': '${base}llms.txt',
      'description':
          'Concise AI-readable project identity and authoritative links.',
    },
    {
      'title': 'llms-full.txt',
      'url': '${base}llms-full.txt',
      'description':
          'Full AI-readable context with algorithms, docs, and validation commands.',
    },
    {
      'title': 'identity.json',
      'url': '${base}identity.json',
      'description':
          'Structured software identity, capabilities, and claim boundary.',
    },
    {
      'title': 'developer-ai.txt',
      'url': '${base}developer-ai.txt',
      'description':
          'Coding-agent guidance for implementation and verification.',
    },
    {
      'title': 'faq-ai.txt',
      'url': '${base}faq-ai.txt',
      'description':
          'AI-readable answers to common package and security questions.',
    },
    {
      'title': 'ai.txt',
      'url': '${base}ai.txt',
      'description': 'Allowed and disallowed AI summarization behavior.',
    },
  ];
}

String _repoBlob(JsonMap project, String path) {
  return '${project['repository']}/blob/${project['repository_branch']}/$path';
}

JsonMap _map(Object? value) => value as JsonMap;

List<JsonMap> _maps(Object? value) => (value as List).cast<JsonMap>();

List<String> _strings(Object? value) => (value as List).cast<String>();

String _mdComment() => '<!-- $_generatedNotice -->\n';

String _hashComment() => '# $_generatedNotice\n';

String _html(Object? value) {
  return value
      .toString()
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;');
}

String _xml(Object? value) {
  return _html(value).replaceAll("'", '&apos;');
}

String _scriptJson(Object value) {
  return jsonEncode(value)
      .replaceAll('<', r'\u003c')
      .replaceAll('>', r'\u003e')
      .replaceAll('&', r'\u0026');
}
